### ISSUE TITLE
Does not highlight the comment text, when install figma plus

### ISSUE THREAD

**Issue by neodisa** [jackiecorn/figma-find-and-replace#1]
Does not selecting the comment text, when installing **figma plus**. If you remove it, everything works

**Comment by jackiecorn** [comment]
Can you elaborate the issue? What comment text are you referring to?
Is this an issue on Figma Plus or the Find and Replace plugin?

**Comment by neodisa** [comment]
Example https://www.loom.com/share/522982764885440383f5df1d12e4aef2
I can't highlight text and copy him when having figma plus . I don't understand from which plugin it not working

**Comment by jackiecorn** [comment]
I see. Thanks for reporting.
I have fixed the bug in Figma Plus, please restart your app and see if it works.
