### ISSUE TITLE
Input field unresponsive and freezes Figma desktop app...

### ISSUE THREAD

**Issue by TBiddy** [jackiecorn/figma-find-and-replace#2]
The input field in Find and Replace has not been responsive and freezes all actions in Figma aside from the Finder menu. I have restarted Figma multiple times, restarted my computer, uninstalled and reinstalled the plugin and the behavior is still the same.

I will try the Chrome version, but currently the Desktop app version (on Mac) doesn't appear to be working.

**Comment by jackiecorn** [comment]
I have updated the plugin with a fix for this issue. 
Please check it out and let me know how it goes.

**Comment by TBiddy** [comment]
This worked! Thank you!
